plugins {
    id 'com.gradleup.shadow' version '9.1.0'
}

import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

dependencies {
    implementation project(':api')
    implementation project(':v1_8_R3')

    implementation 'fr.mrmicky:fastboard:2.1.5'
    implementation 'cc.meteormc:bookapi:1.0.2'
    implementation 'net.byteflux:libby-bukkit:1.3.0'
    implementation 'org.bstats:bstats-bukkit:3.0.2'

    compileOnly 'com.zaxxer:HikariCP:7.0.2'
    compileOnly "org.spigotmc:spigot:1.8.8-R0.1-SNAPSHOT"
    compileOnly 'me.clip:placeholderapi:2.11.6'
    compileOnly 'de.simonsator:Party-and-Friends-MySQL-Edition-Spigot-API:1.6.2-RELEASE'
    compileOnly 'de.simonsator:spigot-party-api-for-party-and-friends:1.0.7-RELEASE'
}

repositories {
    maven { url = 'https://repo.extendedclip.com/releases/' }
    maven { url = 'https://simonsator.de/repo/' }
    maven { url = "https://repo.codemc.io/repository/nms/" }
    maven { url = "https://repo.alessiodp.com/releases/" }
}

processResources {
    inputs.property("version", version)

    filesMatching("plugin.yml") {
        expand(version: version)
    }
}

tasks.named('shadowJar', ShadowJar) {
    archiveFileName = "LiarsLounge-${project.version}.jar"
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    rootProject.subprojects
            .findAll { it.path != project.path }
            .each { module ->
                dependsOn module.tasks.named('jar')
                from {
                    zipTree(module.tasks.named('jar').get().archiveFile.get().asFile)
                }
            }

    relocate 'fr.mrmicky.fastboard', 'com.kooy29.liarslounge.libraries.fastboard'
    relocate 'cc.meteormc.bookapi', 'com.kooy29.liarslounge.libraries.bookapi'
    relocate 'net.byteflux.libby', 'com.kooy29.liarslounge.libraries.libby'
    relocate 'org.bstats', 'com.kooy29.liarslounge.libraries.bstats'
}