dependencies {
    compileOnly project(':api')
    compileOnly('org.spigotmc:spigot:1.21.11-R0.1-SNAPSHOT') {
        exclude group: 'commons-lang', module: 'commons-lang'
    }
}

repositories {
    maven { url = uri('https://repo.codemc.io/repository/nms/') } // Spigot
    maven { url = uri('https://repo.papermc.io/repository/maven-public/') } // com.mojang (dep of Spigot)
}

tasks.named('compileJava', JavaCompile) {
    options.release = 21
}